import { toast } from "react-toastify";

export const topics = [
  "General",
  "Angular",
  "Ant Design",
  "Apollo Server",
  "AWS Lambda",
  "Babel",
  "Backend",
  "Bootstrap",
  "C# (.NET Core)",
  "CI/CD",
  "CSS",
  "CSS-in-JS",
  "Caching Strategies",
  "D3.js",
  "Design Libraries",
  "Django",
  "Docker",
  "Express.js",
  "FastAPI",
  "Firebase",
  "Flask",
  "Frontend",
  "Go (Golang)",
  "Google Cloud Functions",
  "GraphQL",
  "HTML",
  "Java",
  "JavaScript",
  "JWT (JSON Web Tokens)",
  "jQuery",
  "Kubernetes",
  "Laravel",
  "Less",
  "Material-UI",
  "Microservices",
  "MongoDB",
  "MySQL",
  "NEXT.JS",
  "NestJS",
  "Node.js",
  "Nuxt",
  "OAuth",
  "OpenAPI (Swagger)",
  "Passport.js",
  "PostgreSQL",
  "Prisma",
  "Progressive Web Apps (PWA)",
  "Python (Flask, Django)",
  "React",
  "Redis",
  "Responsive Design",
  "Ruby on Rails",
  "Rust (for backend development)",
  "STYLUS",
  "Sass",
  "Service Workers",
  "Socket.IO",
  "Spring Boot",
  "Styled Components",
  "Storybook",
  "Stylus",
  "Symfony",
  "TAILWIND CSS",
  "Three.js",
  "TypeScript",
  "Vue.js",
  "WebAssembly",
  "WebRTC",
  "WebSockets",
  "Webpack",
  "gRPC",
  "UI/UX",
  "Other",
];

export const handleGoogleLogin = () => {
  window.location.href = `${import.meta.env.VITE_BACKEND_URL}/google/login`;
};

export const handleCatch = (error) => {
  toast.error(error?.data?.message);
  console.log(error);
};
