import { toast } from "react-toastify";

export const topics = [
  "General",
  
  // Frontend
  "HTML",
  "CSS",
  "JavaScript",
  "TypeScript",
  "React",
  "Angular",
  "Vue.js",
  "Sass",
  "Less",
  "Stylus",
  "Bootstrap",
  "Tailwind CSS",
  "Webpack",
  "Babel",
  "Redux",
  "GraphQL",
  "D3.js",
  "Three.js",
  "jQuery",
  "Responsive Design",
  "Progressive Web Apps (PWA)",
  "WebAssembly",
  "WebRTC",
  "Service Workers",
  "WebSockets",
  "CSS-in-JS",
  "Material-UI",
  "Ant Design",
  "Styled Components",
  "Storybook",

  // Backend
  "Node.js",
  "Express.js",
  "Django",
  "Flask",
  "Ruby on Rails",
  "Spring Boot",
  "ASP.NET",
  "Laravel",
  "Symfony",
  "FastAPI",
  "NestJS",
  "GraphQL (Server)",
  "RESTful APIs",
  "Socket.IO",
  "Deno",
  "Serverless Framework",
  "AWS Lambda",
  "Google Cloud Functions",
  "Firebase",
  "MongoDB",
  "MySQL",
  "PostgreSQL",
  "SQLite",
  "Redis",
  "Elasticsearch",
  "GraphQL (Database)",
  "Apollo Server",
  "Prisma",
  "ORM (Object-Relational Mapping)",
  "JWT (JSON Web Tokens)",
  "OAuth",
  "Passport.js",
  "Docker",
  "Kubernetes",
  "CI/CD",
  "Microservices",
  "RabbitMQ",
  "GraphQL Subscriptions",
  "WebSockets",
  "Caching Strategies",
  "Server-Side Rendering (SSR)",
  "GraphQL Federation",
  "OpenAPI (Swagger)",
  "gRPC",
  "Rust (for backend development)",
  "Go (Golang)",
  "Python (Flask, Django)",
  "Java",
  "C# (.NET Core)",
];

export const handleGoogleLogin = () => {
  window.location.href = `${import.meta.env.VITE_BACKEND_URL}/google/login`;
};

export const handleCatch = (error) => {
  toast.error(error?.data?.message);
  console.log(error);
};
